// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dns_manager.proto

package dnsmgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PrimaryNs     string                 `protobuf:"bytes,2,opt,name=primary_ns,json=primaryNs,proto3" json:"primary_ns,omitempty"`
	AdminEmail    string                 `protobuf:"bytes,3,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	Serial        int64                  `protobuf:"varint,4,opt,name=serial,proto3" json:"serial,omitempty"`
	Refresh       int32                  `protobuf:"varint,5,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Retry         int32                  `protobuf:"varint,6,opt,name=retry,proto3" json:"retry,omitempty"`
	Expire        int32                  `protobuf:"varint,7,opt,name=expire,proto3" json:"expire,omitempty"`
	MinimumTtl    int32                  `protobuf:"varint,8,opt,name=minimum_ttl,json=minimumTtl,proto3" json:"minimum_ttl,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_dns_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{0}
}

func (x *Zone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zone) GetPrimaryNs() string {
	if x != nil {
		return x.PrimaryNs
	}
	return ""
}

func (x *Zone) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *Zone) GetSerial() int64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *Zone) GetRefresh() int32 {
	if x != nil {
		return x.Refresh
	}
	return 0
}

func (x *Zone) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *Zone) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *Zone) GetMinimumTtl() int32 {
	if x != nil {
		return x.MinimumTtl
	}
	return 0
}

func (x *Zone) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Zone) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Ttl           int32                  `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Rdata         string                 `protobuf:"bytes,5,opt,name=rdata,proto3" json:"rdata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_dns_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Record) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Record) GetRdata() string {
	if x != nil {
		return x.Rdata
	}
	return ""
}

func (x *Record) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PrimaryNs     string                 `protobuf:"bytes,2,opt,name=primary_ns,json=primaryNs,proto3" json:"primary_ns,omitempty"`
	AdminEmail    string                 `protobuf:"bytes,3,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	Refresh       int32                  `protobuf:"varint,4,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Retry         int32                  `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	Expire        int32                  `protobuf:"varint,6,opt,name=expire,proto3" json:"expire,omitempty"`
	MinimumTtl    int32                  `protobuf:"varint,7,opt,name=minimum_ttl,json=minimumTtl,proto3" json:"minimum_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateZoneRequest) Reset() {
	*x = CreateZoneRequest{}
	mi := &file_dns_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateZoneRequest) ProtoMessage() {}

func (x *CreateZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateZoneRequest.ProtoReflect.Descriptor instead.
func (*CreateZoneRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{2}
}

func (x *CreateZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateZoneRequest) GetPrimaryNs() string {
	if x != nil {
		return x.PrimaryNs
	}
	return ""
}

func (x *CreateZoneRequest) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *CreateZoneRequest) GetRefresh() int32 {
	if x != nil {
		return x.Refresh
	}
	return 0
}

func (x *CreateZoneRequest) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *CreateZoneRequest) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *CreateZoneRequest) GetMinimumTtl() int32 {
	if x != nil {
		return x.MinimumTtl
	}
	return 0
}

type GetZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneRequest) Reset() {
	*x = GetZoneRequest{}
	mi := &file_dns_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneRequest) ProtoMessage() {}

func (x *GetZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneRequest.ProtoReflect.Descriptor instead.
func (*GetZoneRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteZoneRequest) Reset() {
	*x = DeleteZoneRequest{}
	mi := &file_dns_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteZoneRequest) ProtoMessage() {}

func (x *DeleteZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteZoneRequest.ProtoReflect.Descriptor instead.
func (*DeleteZoneRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PrimaryNs     string                 `protobuf:"bytes,2,opt,name=primary_ns,json=primaryNs,proto3" json:"primary_ns,omitempty"`
	AdminEmail    string                 `protobuf:"bytes,3,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	Refresh       int32                  `protobuf:"varint,4,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Retry         int32                  `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	Expire        int32                  `protobuf:"varint,6,opt,name=expire,proto3" json:"expire,omitempty"`
	MinimumTtl    int32                  `protobuf:"varint,7,opt,name=minimum_ttl,json=minimumTtl,proto3" json:"minimum_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateZoneRequest) Reset() {
	*x = UpdateZoneRequest{}
	mi := &file_dns_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateZoneRequest) ProtoMessage() {}

func (x *UpdateZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateZoneRequest.ProtoReflect.Descriptor instead.
func (*UpdateZoneRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateZoneRequest) GetPrimaryNs() string {
	if x != nil {
		return x.PrimaryNs
	}
	return ""
}

func (x *UpdateZoneRequest) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *UpdateZoneRequest) GetRefresh() int32 {
	if x != nil {
		return x.Refresh
	}
	return 0
}

func (x *UpdateZoneRequest) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *UpdateZoneRequest) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *UpdateZoneRequest) GetMinimumTtl() int32 {
	if x != nil {
		return x.MinimumTtl
	}
	return 0
}

type ListZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesRequest) Reset() {
	*x = ListZonesRequest{}
	mi := &file_dns_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesRequest) ProtoMessage() {}

func (x *ListZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesRequest.ProtoReflect.Descriptor instead.
func (*ListZonesRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ListZonesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListZonesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*Zone                `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesResponse) Reset() {
	*x = ListZonesResponse{}
	mi := &file_dns_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesResponse) ProtoMessage() {}

func (x *ListZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesResponse.ProtoReflect.Descriptor instead.
func (*ListZonesResponse) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{7}
}

func (x *ListZonesResponse) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *ListZonesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Ttl           int32                  `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Rdata         string                 `protobuf:"bytes,5,opt,name=rdata,proto3" json:"rdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_dns_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRecordRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *CreateRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRecordRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateRecordRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *CreateRecordRequest) GetRdata() string {
	if x != nil {
		return x.Rdata
	}
	return ""
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Rdata         string                 `protobuf:"bytes,4,opt,name=rdata,proto3" json:"rdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_dns_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRecordRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *DeleteRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteRecordRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeleteRecordRequest) GetRdata() string {
	if x != nil {
		return x.Rdata
	}
	return ""
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_dns_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{10}
}

func (x *ListRecordsRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ListRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_dns_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{11}
}

func (x *ListRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsRequest) Reset() {
	*x = GetRecordsRequest{}
	mi := &file_dns_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsRequest) ProtoMessage() {}

func (x *GetRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return file_dns_manager_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecordsRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *GetRecordsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRecordsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_dns_manager_proto protoreflect.FileDescriptor

const file_dns_manager_proto_rawDesc = "" +
	"\n" +
	"\x11dns_manager.proto\x12\vdns_manager\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x02\n" +
	"\x04Zone\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"primary_ns\x18\x02 \x01(\tR\tprimaryNs\x12\x1f\n" +
	"\vadmin_email\x18\x03 \x01(\tR\n" +
	"adminEmail\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\x03R\x06serial\x12\x18\n" +
	"\arefresh\x18\x05 \x01(\x05R\arefresh\x12\x14\n" +
	"\x05retry\x18\x06 \x01(\x05R\x05retry\x12\x16\n" +
	"\x06expire\x18\a \x01(\x05R\x06expire\x12\x1f\n" +
	"\vminimum_ttl\x18\b \x01(\x05R\n" +
	"minimumTtl\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa7\x01\n" +
	"\x06Record\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x05R\x03ttl\x12\x14\n" +
	"\x05rdata\x18\x05 \x01(\tR\x05rdata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd0\x01\n" +
	"\x11CreateZoneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"primary_ns\x18\x02 \x01(\tR\tprimaryNs\x12\x1f\n" +
	"\vadmin_email\x18\x03 \x01(\tR\n" +
	"adminEmail\x12\x18\n" +
	"\arefresh\x18\x04 \x01(\x05R\arefresh\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x05R\x05retry\x12\x16\n" +
	"\x06expire\x18\x06 \x01(\x05R\x06expire\x12\x1f\n" +
	"\vminimum_ttl\x18\a \x01(\x05R\n" +
	"minimumTtl\"$\n" +
	"\x0eGetZoneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x11DeleteZoneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xd0\x01\n" +
	"\x11UpdateZoneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"primary_ns\x18\x02 \x01(\tR\tprimaryNs\x12\x1f\n" +
	"\vadmin_email\x18\x03 \x01(\tR\n" +
	"adminEmail\x12\x18\n" +
	"\arefresh\x18\x04 \x01(\x05R\arefresh\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x05R\x05retry\x12\x16\n" +
	"\x06expire\x18\x06 \x01(\x05R\x06expire\x12\x1f\n" +
	"\vminimum_ttl\x18\a \x01(\x05R\n" +
	"minimumTtl\"N\n" +
	"\x10ListZonesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"d\n" +
	"\x11ListZonesResponse\x12'\n" +
	"\x05zones\x18\x01 \x03(\v2\x11.dns_manager.ZoneR\x05zones\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"y\n" +
	"\x13CreateRecordRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x05R\x03ttl\x12\x14\n" +
	"\x05rdata\x18\x05 \x01(\tR\x05rdata\"g\n" +
	"\x13DeleteRecordRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05rdata\x18\x04 \x01(\tR\x05rdata\"E\n" +
	"\x12ListRecordsRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"D\n" +
	"\x13ListRecordsResponse\x12-\n" +
	"\arecords\x18\x01 \x03(\v2\x13.dns_manager.RecordR\arecords\"O\n" +
	"\x11GetRecordsRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type2\x8e\x05\n" +
	"\n" +
	"DNSManager\x12?\n" +
	"\n" +
	"CreateZone\x12\x1e.dns_manager.CreateZoneRequest\x1a\x11.dns_manager.Zone\x129\n" +
	"\aGetZone\x12\x1b.dns_manager.GetZoneRequest\x1a\x11.dns_manager.Zone\x12?\n" +
	"\n" +
	"UpdateZone\x12\x1e.dns_manager.UpdateZoneRequest\x1a\x11.dns_manager.Zone\x12D\n" +
	"\n" +
	"DeleteZone\x12\x1e.dns_manager.DeleteZoneRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\tListZones\x12\x1d.dns_manager.ListZonesRequest\x1a\x1e.dns_manager.ListZonesResponse\x12E\n" +
	"\fCreateRecord\x12 .dns_manager.CreateRecordRequest\x1a\x13.dns_manager.Record\x12H\n" +
	"\fDeleteRecord\x12 .dns_manager.DeleteRecordRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\vListRecords\x12\x1f.dns_manager.ListRecordsRequest\x1a .dns_manager.ListRecordsResponse\x12N\n" +
	"\n" +
	"GetRecords\x12\x1e.dns_manager.GetRecordsRequest\x1a .dns_manager.ListRecordsResponseB(Z&github.com/Adatage/ShardDNS/api;dnsmgrb\x06proto3"

var (
	file_dns_manager_proto_rawDescOnce sync.Once
	file_dns_manager_proto_rawDescData []byte
)

func file_dns_manager_proto_rawDescGZIP() []byte {
	file_dns_manager_proto_rawDescOnce.Do(func() {
		file_dns_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dns_manager_proto_rawDesc), len(file_dns_manager_proto_rawDesc)))
	})
	return file_dns_manager_proto_rawDescData
}

var file_dns_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dns_manager_proto_goTypes = []any{
	(*Zone)(nil),                  // 0: dns_manager.Zone
	(*Record)(nil),                // 1: dns_manager.Record
	(*CreateZoneRequest)(nil),     // 2: dns_manager.CreateZoneRequest
	(*GetZoneRequest)(nil),        // 3: dns_manager.GetZoneRequest
	(*DeleteZoneRequest)(nil),     // 4: dns_manager.DeleteZoneRequest
	(*UpdateZoneRequest)(nil),     // 5: dns_manager.UpdateZoneRequest
	(*ListZonesRequest)(nil),      // 6: dns_manager.ListZonesRequest
	(*ListZonesResponse)(nil),     // 7: dns_manager.ListZonesResponse
	(*CreateRecordRequest)(nil),   // 8: dns_manager.CreateRecordRequest
	(*DeleteRecordRequest)(nil),   // 9: dns_manager.DeleteRecordRequest
	(*ListRecordsRequest)(nil),    // 10: dns_manager.ListRecordsRequest
	(*ListRecordsResponse)(nil),   // 11: dns_manager.ListRecordsResponse
	(*GetRecordsRequest)(nil),     // 12: dns_manager.GetRecordsRequest
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_dns_manager_proto_depIdxs = []int32{
	13, // 0: dns_manager.Zone.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: dns_manager.Zone.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: dns_manager.Record.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: dns_manager.ListZonesResponse.zones:type_name -> dns_manager.Zone
	1,  // 4: dns_manager.ListRecordsResponse.records:type_name -> dns_manager.Record
	2,  // 5: dns_manager.DNSManager.CreateZone:input_type -> dns_manager.CreateZoneRequest
	3,  // 6: dns_manager.DNSManager.GetZone:input_type -> dns_manager.GetZoneRequest
	5,  // 7: dns_manager.DNSManager.UpdateZone:input_type -> dns_manager.UpdateZoneRequest
	4,  // 8: dns_manager.DNSManager.DeleteZone:input_type -> dns_manager.DeleteZoneRequest
	6,  // 9: dns_manager.DNSManager.ListZones:input_type -> dns_manager.ListZonesRequest
	8,  // 10: dns_manager.DNSManager.CreateRecord:input_type -> dns_manager.CreateRecordRequest
	9,  // 11: dns_manager.DNSManager.DeleteRecord:input_type -> dns_manager.DeleteRecordRequest
	10, // 12: dns_manager.DNSManager.ListRecords:input_type -> dns_manager.ListRecordsRequest
	12, // 13: dns_manager.DNSManager.GetRecords:input_type -> dns_manager.GetRecordsRequest
	0,  // 14: dns_manager.DNSManager.CreateZone:output_type -> dns_manager.Zone
	0,  // 15: dns_manager.DNSManager.GetZone:output_type -> dns_manager.Zone
	0,  // 16: dns_manager.DNSManager.UpdateZone:output_type -> dns_manager.Zone
	14, // 17: dns_manager.DNSManager.DeleteZone:output_type -> google.protobuf.Empty
	7,  // 18: dns_manager.DNSManager.ListZones:output_type -> dns_manager.ListZonesResponse
	1,  // 19: dns_manager.DNSManager.CreateRecord:output_type -> dns_manager.Record
	14, // 20: dns_manager.DNSManager.DeleteRecord:output_type -> google.protobuf.Empty
	11, // 21: dns_manager.DNSManager.ListRecords:output_type -> dns_manager.ListRecordsResponse
	11, // 22: dns_manager.DNSManager.GetRecords:output_type -> dns_manager.ListRecordsResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dns_manager_proto_init() }
func file_dns_manager_proto_init() {
	if File_dns_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dns_manager_proto_rawDesc), len(file_dns_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dns_manager_proto_goTypes,
		DependencyIndexes: file_dns_manager_proto_depIdxs,
		MessageInfos:      file_dns_manager_proto_msgTypes,
	}.Build()
	File_dns_manager_proto = out.File
	file_dns_manager_proto_goTypes = nil
	file_dns_manager_proto_depIdxs = nil
}
